import{a as M,S as P,i}from"./assets/vendor-BLPZKqeQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const E="50342970-c77e3a3b99b31ba7a45091d0e",R="https://pixabay.com/api/";async function d(o,t=1,a=15){try{return(await M.get(R,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}})).data}catch(s){throw console.error("Sorry, there are no images matching your search query. Please try again!",s),s}}const u=document.querySelector(".gallery"),h=document.querySelector(".loader"),_=new P(".gallery a",{captionsData:"alt",captionDelay:250});function f(o){const t=o.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:c,comments:S,downloads:q})=>`
    <div class="photo-card">
      <a class="gallery__item" href="${s}">
        <img class="gallery__image" src="${a}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${c}</p>
        <p><b>Comments:</b> ${S}</p>
        <p><b>Downloads:</b> ${q}</p>
      </div>
    </div>
  `).join("");u.insertAdjacentHTML("beforeend",t),_.refresh()}function $(){u.innerHTML=""}function g(){h.classList.remove("hidden")}function m(){h.classList.add("hidden")}const p=document.querySelector(".load-more"),y=document.querySelector(".loader2-message");function L(){p.classList.add("hidden")}console.log("Showind load more button");function b(){p.classList.remove("hidden")}function B(){y.classList.remove("hidden")}console.log('Showing "Loading images, please wait..."');function O(){y.classList.add("hidden")}function x(){const o=document.querySelector(".photo-card");if(!o)return;const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}const w=document.querySelector("#search-form"),A=w.querySelector('input[name="search-text"]'),H=document.querySelector(".load-more");let l="",n=1;const v=15;w.addEventListener("submit",async o=>{if(o.preventDefault(),l=A.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}n=1,$(),L(),g();try{const t=await d(l,n);if(t.hits.length===0){i.info({title:"No results",message:"No images found for this query.",position:"topRight"});return}f(t.hits);const a=Math.ceil(t.totalHits/v);n<a?b():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{m()}});H.addEventListener("click",async()=>{n+=1,g(),B(),L();try{const o=await d(l,n);f(o.hits),x();const t=Math.ceil(o.totalHits/v);n<t?b():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{m(),O()}});
//# sourceMappingURL=index.js.map
