import{a as q,S as P,i}from"./assets/vendor-BLPZKqeQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const E="50342970-c77e3a3b99b31ba7a45091d0e",M="https://pixabay.com/api/";async function d(r,t=1,s=15){return q.get(M,{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}}).then(a=>a.data).catch(a=>{throw console.error("Sorry, there are no images matching your search query. Please try again!",a),a})}const u=document.querySelector(".gallery"),h=document.querySelector(".loader"),_=new P(".gallery a",{captionsData:"alt",captionDelay:250});function f(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:l,comments:S,downloads:w})=>`
    <div class="photo-card">
      <a class="gallery__item" href="${a}">
        <img class="gallery__image" src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${l}</p>
        <p><b>Comments:</b> ${S}</p>
        <p><b>Downloads:</b> ${w}</p>
      </div>
    </div>
  `).join("");u.insertAdjacentHTML("beforeend",t),_.refresh()}function $(){u.innerHTML=""}function m(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}const p=document.querySelector(".load-more");document.querySelector(".loader2-message");function y(){p.classList.add("hidden")}console.log("Showind load more button");function b(){p.classList.remove("hidden")}console.log('Showing "Loading images, please wait..."');const L=document.querySelector("#search-form"),R=L.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let c="",n=1;const v=15;L.addEventListener("submit",async r=>{if(r.preventDefault(),c=R.value.trim(),!c){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}n=1,$(),y(),m();try{const t=await d(c,n);if(t.hits.length===0){i.info({title:"No results",message:"No images found for this query.",position:"topRight"});return}f(t.hits);const s=Math.ceil(t.totalHits/v);n<s?b():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{g()}});O.addEventListener("click",async()=>{n+=1,m(),y();try{const r=await d(c,n);f(r.hits);const t=Math.ceil(r.totalHits/v);n<t?b():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{g()}});
//# sourceMappingURL=index.js.map
