import{a as q,S as P,i}from"./assets/vendor-BLPZKqeQ.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const E="50342970-c77e3a3b99b31ba7a45091d0e",M="https://pixabay.com/api/";async function d(o,t=1,s=15){return q.get(M,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:s}}).then(a=>a.data).catch(a=>{throw console.error("Sorry, there are no images matching your search query. Please try again!",a),a})}const u=document.querySelector(".gallery"),h=document.querySelector(".loader"),R=new P(".gallery a",{captionsData:"alt",captionDelay:250});function f(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:c,comments:w,downloads:S})=>`
    <div class="photo-card">
      <a class="gallery__item" href="${a}">
        <img class="gallery__image" src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r}</p>
        <p><b>Views:</b> ${c}</p>
        <p><b>Comments:</b> ${w}</p>
        <p><b>Downloads:</b> ${S}</p>
      </div>
    </div>
  `).join("");u.insertAdjacentHTML("beforeend",t),R.refresh()}function _(){u.innerHTML=""}function g(){h.classList.remove("hidden")}function m(){h.classList.add("hidden")}const p=document.querySelector(".load-more");document.querySelector(".loader2-message");function y(){p.classList.add("hidden")}console.log("Showind load more button");function b(){p.classList.remove("hidden")}console.log('Showing "Loading images, please wait..."');function $(){const o=document.querySelector(".gallery-item");if(!o)return;const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}const L=document.querySelector("#search-form"),B=L.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let l="",n=1;const v=15;L.addEventListener("submit",async o=>{if(o.preventDefault(),l=B.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}n=1,_(),y(),g();try{const t=await d(l,n);if(t.hits.length===0){i.info({title:"No results",message:"No images found for this query.",position:"topRight"});return}f(t.hits);const s=Math.ceil(t.totalHits/v);n<s?b():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{m()}});O.addEventListener("click",async()=>{n+=1,g(),y();try{const o=await d(l,n);f(o.hits),$();const t=Math.ceil(o.totalHits/v);n<t?b():i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{m()}});
//# sourceMappingURL=index.js.map
